"""The only doors to the outside world (docs/ARCHITECTURE.md §3).

Each port has a fake (tests), a local adapter and a cloud adapter; method names are binding.
Argument and return types marked "settles in STEP-NN" are refined by the lane that builds the
first adapter, in this file.
"""

from collections.abc import Mapping, Sequence
from datetime import datetime
from pathlib import Path
from typing import Protocol

# Payload shapes settle with their first adapter (STEP-03 for Claude and Gemini, STEP-06 for the
# website ports). Until then a port speaks in plain mappings.
Record = Mapping[str, object]
UploadTarget = Record  # settles in STEP-06


class Storage(Protocol):
    def create_upload_session(self, order_id: str, file: Record) -> UploadTarget: ...
    def list_inputs(self, order_id: str) -> Sequence[Record]: ...
    def download(self, key: str, path: Path) -> None: ...
    def upload(self, path: Path, key: str, content_type: str) -> None: ...
    def signed_url(self, key: str, filename: str, minutes: int) -> str: ...
    def delete_order(self, order_id: str) -> None: ...


class Orders(Protocol):
    # Keyword fields settle in STEP-06 with the Firestore document (ARCHITECTURE.md §4).
    def create_awaiting_payment(self, **fields: object) -> str: ...
    def mark_paid(self, order_id: str, stripe: Record) -> None: ...
    def expire(self, order_id: str) -> None: ...
    def set_manifest(self, order_id: str, **fields: object) -> None: ...
    def queue(self, order_id: str) -> None: ...
    def take_slot(self, order_id: str) -> bool: ...
    def release_slot(self, order_id: str) -> None: ...
    def next_queued(self) -> str | None: ...
    def set_stage(self, order_id: str, **fields: object) -> None: ...
    def finish(self, order_id: str, **fields: object) -> None: ...
    def fail(self, order_id: str, **fields: object) -> None: ...
    def pause(self, order_id: str, **fields: object) -> None: ...
    def get(self, order_id: str) -> Record | None: ...


class Launcher(Protocol):
    def launch(self, order_id: str) -> str: ...


class Mailer(Protocol):
    def send(self, template: str, to: str, data: Record) -> None: ...


class Payments(Protocol):
    def find_code(self, code: str) -> Record | None: ...
    def create_checkout(
        self, order_id: str, promo_id: str, urls: Record, expires_at: datetime
    ) -> Record: ...
    def parse_webhook(self, payload: bytes, signature: str) -> Record: ...
    def get_session(self, session_id: str) -> Record: ...


class Claude(Protocol):
    def count_tokens(self, request: Record) -> int: ...
    def create(self, request: Record) -> Record: ...


class Transcriber(Protocol):
    def transcribe(self, audio_path: Path, timestamps: bool = True) -> Record: ...


class Clock(Protocol):
    def now(self) -> datetime: ...
